### ISSUE TITLE
Can't put clips together

### ISSUE THREAD

**Issue by computer2467** [philosophofee/YTPPlus#3]
This happens for whatever configuration or media I use and I do have ffmpeg, ffprobe, and imagemagick configured properly. After it says that every clip exists, it outputs this:
`MediaException: MEDIA_UNAVAILABLE : C:\Users\<USER>\Downloads\YTPPLUSBETA1\temp\tempoutput.mp4 (The system cannot find the file specified)
        at javafx.scene.media.Media.<init>(Media.java:407)
        at ytpplusui.FXMLController$1.run(FXMLController.java:258)`
and then stops with a blank preview screen and a full blue bar.

**Comment by random-player** [comment]
This happens to me aswell, I can _almost_ create the video clip but ends with that error. I wish they would respond but YTP+ 2.0 should probably fix this. But I think I know the reason.

**Comment by KiwifruitDev** [comment]
If your videos do not have spaces, please use FFprobe to see how the video was encoded and let me know. As of right now my node.js port has a UI and prevents users from rendering videos with spaces in them.

**Comment by beefytoes** [comment]
9/8/2020 Having this error. Dont know how to fix it. MediaException: MEDIA_UNAVAILABLE : C:\Users\****\OneDrive\Desktop\YTPPLUSBETA1\temp\tempoutput.mp4 (The system cannot find the file specified)
